# this is the build file for project picoc
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CC=/usr/bin/gcc
CU=/opt/cuda/bin/nvcc
RC=/usr/bin/rustc
MXX=/usr/bin/gcc
MM=/usr/bin/gcc
AS=/usr/bin/gcc
GC=/usr/bin/go
CXX=/usr/bin/gcc

LD=/usr/bin/g++
GCLD=/usr/bin/go
RCLD=/usr/bin/rustc
CULD=/opt/cuda/bin/nvcc
SH=/usr/bin/g++
RCSH=/usr/bin/rustc
AR=/usr/bin/ar
GCAR=/usr/bin/go
RCAR=/usr/bin/rustc


picoc_CCFLAGS=-m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/picoc/linux/x86_64/release/rules/yacc_yacc -std=c99 -DNDEBUG
picoc_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -lpicolang
picolang_CCFLAGS=-m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -std=c99 -DNDEBUG
picolang_ARFLAGS=-cr

default:  picoc picolang

all:  picoc picolang

.PHONY: default all  picoc picolang

precmds_picoc:
	@mkdir -p build/.gens/picoc/linux/x86_64/release/rules/yacc_yacc
	$(VV)/usr/bin/bison -d -o build/.gens/picoc/linux/x86_64/release/rules/yacc_yacc/parser.tab.c src/picolang/parser.y
	@mkdir -p build/.objs/picoc/linux/x86_64/release/gens/rules/yacc_yacc
	$(VV)/usr/bin/gcc -c -m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/picoc/linux/x86_64/release/rules/yacc_yacc -std=c99 -DNDEBUG -o build/.objs/picoc/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.gens/picoc/linux/x86_64/release/rules/yacc_yacc/parser.tab.c
	@mkdir -p build/.gens/picoc/linux/x86_64/release/rules/lex_yacc
	$(VV)/usr/bin/flex -o build/.gens/picoc/linux/x86_64/release/rules/lex_yacc/lexer.c src/picolang/lexer.l
	@mkdir -p build/.objs/picoc/linux/x86_64/release/gens/rules/lex_yacc
	$(VV)/usr/bin/gcc -c -m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/picoc/linux/x86_64/release/rules/yacc_yacc -std=c99 -DNDEBUG -o build/.objs/picoc/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o build/.gens/picoc/linux/x86_64/release/rules/lex_yacc/lexer.c

picoc: precmds_picoc precmds_picoc build/linux/x86_64/release/libpicolang.a build/.objs/picoc/linux/x86_64/release/src/main.c.o build/.objs/picoc/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.objs/picoc/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o
	@echo linking.release picoc
	@mkdir -p .
	$(VV)$(LD) -o picoc build/.objs/picoc/linux/x86_64/release/src/main.c.o build/.objs/picoc/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.objs/picoc/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o $(picoc_LDFLAGS)

build/.objs/picoc/linux/x86_64/release/src/main.c.o: precmds_picoc src/main.c
	@echo ccache compiling.release src/main.c
	@mkdir -p build/.objs/picoc/linux/x86_64/release/src
	$(VV)$(CC) -c $(picoc_CCFLAGS) -o build/.objs/picoc/linux/x86_64/release/src/main.c.o src/main.c

picolang: build/linux/x86_64/release/libpicolang.a
build/linux/x86_64/release/libpicolang.a: build/.objs/picolang/linux/x86_64/release/src/picolang/picolang.c.o
	@echo linking.release libpicolang.a
	@mkdir -p build/linux/x86_64/release
	$(VV)$(AR) $(picolang_ARFLAGS) build/linux/x86_64/release/libpicolang.a build/.objs/picolang/linux/x86_64/release/src/picolang/picolang.c.o

build/.objs/picolang/linux/x86_64/release/src/picolang/picolang.c.o: src/picolang/picolang.c
	@echo ccache compiling.release src/picolang/picolang.c
	@mkdir -p build/.objs/picolang/linux/x86_64/release/src/picolang
	$(VV)$(CC) -c $(picolang_CCFLAGS) -o build/.objs/picolang/linux/x86_64/release/src/picolang/picolang.c.o src/picolang/picolang.c

clean:  clean_picoc clean_picolang

clean_picoc:  clean_picolang
	@rm -rf picoc
	@rm -rf picoc.sym
	@rm -rf build/.objs/picoc/linux/x86_64/release/src/main.c.o
	@rm -rf build/.objs/picoc/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o
	@rm -rf build/.objs/picoc/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o

clean_picolang: 
	@rm -rf build/linux/x86_64/release/libpicolang.a
	@rm -rf build/linux/x86_64/release/picolang.sym
	@rm -rf build/.objs/picolang/linux/x86_64/release/src/picolang/picolang.c.o

