#!/bin/bash

usage() {
    echo -e "Usage: $0" 1>&2
    exit 1
}

command_exists() {
    if ! command -v """$1" >/dev/null 2>&1; then
        echo "I require the command ""$1 but it's not installed. Abort."
        exit 1
    fi
}

command_exists "flex"
command_exists "bison"
command_exists "gcc"
command_exists "make"

# Make
make clean && make

# Grab all files in ./assets/code into an array
files=()
for file in ./assets/code/*; do
    files+=("$file")
done

# Print each file and its output
for file in "${files[@]}"; do
  echo "File: $file"
  cat "$file"
  echo -e "\nOutput:"
  ./picoc < "$file"
  echo -e "\n"
done
